-- MySQL Script generated by MySQL Workbench
-- Fri Sep  2 16:08:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ifocop_myshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ifocop_myshop` ;

-- -----------------------------------------------------
-- Schema ifocop_myshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifocop_myshop` DEFAULT CHARACTER SET utf8 ;
USE `ifocop_myshop` ;

-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_address` (
  `id_address` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(255) NOT NULL,
  `postal_code` INT UNSIGNED NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_address`),
  UNIQUE INDEX `id_address_UNIQUE` (`id_address` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_member` (
  `id_member` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(30) NULL DEFAULT NULL,
  `lastname` VARCHAR(30) NULL DEFAULT NULL,
  `gender` ENUM('male', 'female') NULL DEFAULT NULL,
  `phone` INT(11) NULL DEFAULT NULL,
  `role` VARCHAR(30) NOT NULL DEFAULT 'ROLE_MEMBER',
  `last_login` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `newsletter` TINYINT(1) NOT NULL DEFAULT '0',
  `id_billing_address` INT(10) UNSIGNED NULL DEFAULT NULL,
  `id_mailing_address` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_member`),
  UNIQUE INDEX `id_member_UNIQUE` (`id_member` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_myshop_member_myshop_address1_idx` (`id_billing_address` ASC),
  INDEX `fk_myshop_member_myshop_address1_idx1` (`id_mailing_address` ASC),
  CONSTRAINT `fk_billing_address`
    FOREIGN KEY (`id_billing_address`)
    REFERENCES `ifocop_myshop`.`myshop_address` (`id_address`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mailing_address`
    FOREIGN KEY (`id_mailing_address`)
    REFERENCES `ifocop_myshop`.`myshop_address` (`id_address`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_editor` (
  `id_editor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country` VARCHAR(45) NULL,
  `year` YEAR NULL,
  PRIMARY KEY (`id_editor`),
  UNIQUE INDEX `id_editor_UNIQUE` (`id_editor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_game` (
  `id_game` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `id_editor` INT UNSIGNED NOT NULL,
  `release_date` DATE NULL,
  `price` FLOAT NOT NULL,
  `pegi` ENUM('all', '3', '7', '12', '16', '18') NULL DEFAULT NULL,
  `pre_order` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `jacket` VARCHAR(255) NULL,
  PRIMARY KEY (`id_game`),
  UNIQUE INDEX `id_game_UNIQUE` (`id_game` ASC),
  INDEX `fk_game_editor1_idx` (`id_editor` ASC),
  CONSTRAINT `fk_game_editor1`
    FOREIGN KEY (`id_editor`)
    REFERENCES `ifocop_myshop`.`myshop_editor` (`id_editor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_comment` (
  `id_comment` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `id_member` INT(10) UNSIGNED NULL DEFAULT NULL,
  `id_game` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_comment`),
  UNIQUE INDEX `id_comment_UNIQUE` (`id_comment` ASC),
  INDEX `fk_comment_member1_idx` (`id_member` ASC),
  INDEX `fk_myshop_comment_game1_idx` (`id_game` ASC),
  CONSTRAINT `fk_comment_member`
    FOREIGN KEY (`id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_myshop_comment_game1`
    FOREIGN KEY (`id_game`)
    REFERENCES `ifocop_myshop`.`myshop_game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_forum_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_forum_category` (
  `id_category` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `position_weight` TINYINT(3) UNSIGNED NOT NULL DEFAULT '255',
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_forum_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_forum_section` (
  `id_section` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_category` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `nb_posts` INT(10) UNSIGNED NOT NULL,
  `nb_threads` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `last_thread_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_section`),
  UNIQUE INDEX `id_section_UNIQUE` (`id_section` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  INDEX `fk_section_belongs_to_category_idx` (`id_category` ASC),
  CONSTRAINT `fk_section_belongs_to_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `ifocop_myshop`.`myshop_forum_category` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_forum_thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_forum_thread` (
  `id_thread` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_section` INT(10) UNSIGNED NOT NULL,
  `topic` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `nb_posts` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by_id_member` INT(10) UNSIGNED NULL DEFAULT NULL,
  `updated_by_id_member` INT(10) UNSIGNED NULL DEFAULT NULL,
  `last_post_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_thread`),
  UNIQUE INDEX `id_thread_UNIQUE` (`id_thread` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  INDEX `fk_thread_forum_section_idx` (`id_section` ASC),
  INDEX `fk_thread_created_by_member_idx` (`created_by_id_member` ASC),
  INDEX `fk_thread_upated_by_member_idx` (`updated_by_id_member` ASC),
  CONSTRAINT `fk_thread_belongs_to_section`
    FOREIGN KEY (`id_section`)
    REFERENCES `ifocop_myshop`.`myshop_forum_section` (`id_section`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_thread_created_by_member`
    FOREIGN KEY (`created_by_id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_thread_updated_by_member`
    FOREIGN KEY (`updated_by_id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_forum_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_forum_post` (
  `id_post` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by_id_member` INT(10) UNSIGNED NULL DEFAULT NULL,
  `updated_by_id_member` INT(10) UNSIGNED NULL DEFAULT NULL,
  `id_thread` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_post`),
  UNIQUE INDEX `id_post_UNIQUE` (`id_post` ASC),
  INDEX `fk_post_created_by_member_idx` (`created_by_id_member` ASC),
  INDEX `fk_post_updated_by_member_idx` (`updated_by_id_member` ASC),
  INDEX `fk_post_thread_idx` (`id_thread` ASC),
  CONSTRAINT `fk_post_created_by_member`
    FOREIGN KEY (`created_by_id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_thread`
    FOREIGN KEY (`id_thread`)
    REFERENCES `ifocop_myshop`.`myshop_forum_thread` (`id_thread`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_updated_by_member`
    FOREIGN KEY (`updated_by_id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1533
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_genre` (
  `id_genre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`),
  UNIQUE INDEX `id_genre_UNIQUE` (`id_genre` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_platform` (
  `id_platform` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `owner` VARCHAR(45) NULL,
  `release_date` DATE NULL,
  PRIMARY KEY (`id_platform`),
  UNIQUE INDEX `id_platform_UNIQUE` (`id_platform` ASC),
  UNIQUE INDEX `short_name_UNIQUE` (`short_name` ASC),
  UNIQUE INDEX `full_name_UNIQUE` (`full_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_game_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_game_has_genre` (
  `id_game` INT UNSIGNED NOT NULL,
  `id_genre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_game`, `id_genre`),
  INDEX `fk_game_has_genre_genre1_idx` (`id_genre` ASC),
  INDEX `fk_game_has_genre_game1_idx` (`id_game` ASC),
  CONSTRAINT `fk_game_genre_id_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `ifocop_myshop`.`myshop_game` (`id_game`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_game_genre_id_genre`
    FOREIGN KEY (`id_genre`)
    REFERENCES `ifocop_myshop`.`myshop_genre` (`id_genre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_game_has_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_game_has_platform` (
  `id_game` INT UNSIGNED NOT NULL,
  `id_platform` INT UNSIGNED NOT NULL,
  `stock` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_game`, `id_platform`),
  INDEX `fk_game_has_platform_platform1_idx` (`id_platform` ASC),
  INDEX `fk_game_has_platform_game1_idx` (`id_game` ASC),
  CONSTRAINT `fk_game_platform_id_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `ifocop_myshop`.`myshop_game` (`id_game`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_game_platform_id_platform`
    FOREIGN KEY (`id_platform`)
    REFERENCES `ifocop_myshop`.`myshop_platform` (`id_platform`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_order` (
  `id_order` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total` FLOAT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `id_member` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_order`),
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC),
  INDEX `fk_order_myshop_member1_idx` (`id_member` ASC),
  CONSTRAINT `fk_order_myshop_member1`
    FOREIGN KEY (`id_member`)
    REFERENCES `ifocop_myshop`.`myshop_member` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifocop_myshop`.`myshop_order_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifocop_myshop`.`myshop_order_has_game` (
  `id_order` INT UNSIGNED NOT NULL,
  `id_game` INT UNSIGNED NOT NULL,
  `id_platform` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_order`, `id_game`, `id_platform`),
  INDEX `fk_order_has_game_game1_idx` (`id_game` ASC),
  INDEX `fk_order_has_game_order1_idx` (`id_order` ASC),
  INDEX `fk_order_hase_game_platform_idx` (`id_platform` ASC),
  CONSTRAINT `fk_order_has_game_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `ifocop_myshop`.`myshop_order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_game_game`
    FOREIGN KEY (`id_game`)
    REFERENCES `ifocop_myshop`.`myshop_game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_hase_game_platform`
    FOREIGN KEY (`id_platform`)
    REFERENCES `ifocop_myshop`.`myshop_platform` (`id_platform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ifocop_myshop`;

DELIMITER $$
USE `ifocop_myshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `ifocop_myshop`.`AFTER_INSERT_forum_thread`
AFTER INSERT ON `ifocop_myshop`.`myshop_forum_thread`
FOR EACH ROW
BEGIN
        UPDATE myshop_forum_section
        SET
            nb_threads = nb_threads + 1
        WHERE id_section = NEW.id_section;
    END$$

USE `ifocop_myshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `ifocop_myshop`.`AFTER_DELETE_forum_thread`
AFTER DELETE ON `ifocop_myshop`.`myshop_forum_thread`
FOR EACH ROW
BEGIN
        UPDATE myshop_forum_section s
        SET
            last_thread_id = (
                CASE WHEN nb_threads <= 1
                    THEN NULL
                ELSE (
                    SELECT t.id_thread
                    FROM myshop_forum_thread t
                        INNER JOIN myshop_forum_post p ON t.last_post_id = p.id_post
                    WHERE t.id_section = s.id_section
                    ORDER BY p.created_at DESC
                    LIMIT 1
                )
                END
            ),
            nb_threads = nb_threads - 1
        WHERE id_section = OLD.id_section;
    END$$

USE `ifocop_myshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `ifocop_myshop`.`AFTER_INSERT_forum_post`
AFTER INSERT ON `ifocop_myshop`.`myshop_forum_post`
FOR EACH ROW
BEGIN
        UPDATE myshop_forum_thread
        SET
            last_post_id = NEW.id_post,
            nb_posts = nb_posts + 1
        WHERE id_thread = NEW.id_thread;

        UPDATE myshop_forum_section
        SET
            last_thread_id = NEW.id_thread,
            nb_posts = nb_posts + 1
        WHERE id_section = (
            SELECT id_section
            FROM myshop_forum_thread
            WHERE id_thread = NEW.id_thread
        );
END$$

USE `ifocop_myshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `ifocop_myshop`.`AFTER_DELETE_forum_post`
AFTER DELETE ON `ifocop_myshop`.`myshop_forum_post`
FOR EACH ROW
BEGIN
        UPDATE myshop_forum_thread t
        SET
            last_post_id = (
                CASE WHEN nb_posts <= 1
                    THEN NULL
                ELSE (
                    SELECT id_post
                    FROM myshop_forum_post p
                    WHERE p.id_thread = t.id_thread
                    ORDER BY created_at DESC
                    LIMIT 1
                )
                END
            ),
            nb_posts = nb_posts - 1
        WHERE id_thread = OLD.id_thread;
    END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
