-- MySQL Script generated by MySQL Workbench
-- Sat May 21 13:49:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ifocop_myshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS ifocop_myshop ;

-- -----------------------------------------------------
-- Schema ifocop_myshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ifocop_myshop DEFAULT CHARACTER SET utf8 ;
USE ifocop_myshop ;

-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_member
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_member (
    id_member INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    email VARCHAR(45) NOT NULL,
    firstname VARCHAR(30) NULL DEFAULT NULL,
    lastname VARCHAR(30) NULL DEFAULT NULL,
    gender ENUM('male', 'female') NULL DEFAULT NULL,
    phone INT NULL DEFAULT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_MEMBER',
    last_login DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    newsletter TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id_member),
    UNIQUE INDEX id_member_UNIQUE (id_member ASC),
    UNIQUE INDEX username_UNIQUE (username ASC),
    UNIQUE INDEX email_UNIQUE (email ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_address
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_address (
    id_address INT UNSIGNED NOT NULL AUTO_INCREMENT,
    number SMALLINT UNSIGNED NOT NULL,
    street VARCHAR(255) NOT NULL,
    postal_code SMALLINT UNSIGNED NOT NULL,
    city VARCHAR(100) NOT NULL,
    id_member INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_address),
    UNIQUE INDEX id_address_UNIQUE (id_address ASC),
    INDEX fk_address_member_idx (id_member ASC),
    CONSTRAINT fk_address_member
    FOREIGN KEY (id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE CASCADE
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_product
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_product (
    id_product INT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference VARCHAR(10) NOT NULL,
    name VARCHAR(45) NOT NULL,
    description VARCHAR(45) NOT NULL,
    price_no_tax FLOAT NOT NULL,
    PRIMARY KEY (id_product),
    UNIQUE INDEX id_product_UNIQUE (id_product ASC),
    UNIQUE INDEX reference_UNIQUE (reference ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_product_category
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_product_category (
    id_product_category INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NULL,
    PRIMARY KEY (id_product_category),
    UNIQUE INDEX id_product_category_UNIQUE (id_product_category ASC),
    UNIQUE INDEX name_UNIQUE (name ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_note
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_note (
    id_note INT UNSIGNED NOT NULL AUTO_INCREMENT,
    valeur TINYINT UNSIGNED NOT NULL COMMENT 'Integer between 0 and 10',
    created_at DATETIME NOT NULL,
    id_product INT UNSIGNED NOT NULL,
    id_member INT UNSIGNED NULL,
    PRIMARY KEY (id_note),
    UNIQUE INDEX id_note_UNIQUE (id_note ASC),
    INDEX fk_note_product_idx (id_product ASC),
    INDEX fk_note_member_idx (id_member ASC),
    CONSTRAINT fk_note_product
    FOREIGN KEY (id_product)
    REFERENCES ifocop_myshop.myshop_product (id_product)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_note_member
    FOREIGN KEY (id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_product_has_product_category
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_product_has_product_category (
    id_product INT UNSIGNED NOT NULL,
    id_product_category INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_product, id_product_category),
    INDEX fk_product_has_product_category_product_category1_idx (id_product_category ASC),
    INDEX fk_product_has_product_category_product1_idx (id_product ASC),
    CONSTRAINT fk_product_has_product_category_product
    FOREIGN KEY (id_product)
    REFERENCES ifocop_myshop.myshop_product (id_product)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_product_has_product_category_product_category
    FOREIGN KEY (id_product_category)
    REFERENCES ifocop_myshop.myshop_product_category (id_product_category)
        ON DELETE CASCADE
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_comment
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_comment (
    id_comment INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NULL DEFAULT NULL,
    content TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL DEFAULT NULL,
    id_product INT UNSIGNED NULL,
    id_member INT UNSIGNED NULL,
    PRIMARY KEY (id_comment),
    UNIQUE INDEX id_comment_UNIQUE (id_comment ASC),
    INDEX fk_comment_product1_idx (id_product ASC),
    INDEX fk_comment_member1_idx (id_member ASC),
    CONSTRAINT fk_comment_product
    FOREIGN KEY (id_product)
    REFERENCES ifocop_myshop.myshop_product (id_product)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_comment_member
    FOREIGN KEY (id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_order
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_order (
    id_order INT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_label VARCHAR(10) NOT NULL,
    created_at DATETIME NOT NULL,
    total_no_tax FLOAT NOT NULL,
    total_with_tax FLOAT NOT NULL,
    status ENUM('Reçue', 'En préparation', 'Expédiée', 'Livrée') NOT NULL DEFAULT 'Reçue',
    id_member INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_order),
    UNIQUE INDEX id_order_UNIQUE (id_order ASC),
    UNIQUE INDEX order_label_UNIQUE (order_label ASC),
    INDEX fk_order_member_idx (id_member ASC),
    CONSTRAINT fk_order_member
    FOREIGN KEY (id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_product_has_order
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_product_has_order (
    id_product INT UNSIGNED NOT NULL,
    id_order INT UNSIGNED NOT NULL,
    quantity SMALLINT UNSIGNED NOT NULL,
    unit_price_no_tax INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_product, id_order),
    INDEX fk_product_has_order_order1_idx (id_order ASC),
    INDEX fk_product_has_order_product1_idx (id_product ASC),
    CONSTRAINT fk_product_has_order_product1
    FOREIGN KEY (id_product)
    REFERENCES ifocop_myshop.myshop_product (id_product)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_product_has_order_order1
    FOREIGN KEY (id_order)
    REFERENCES ifocop_myshop.myshop_order (id_order)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_forum_category
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_forum_category (
    id_category INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    position_weight TINYINT UNSIGNED NOT NULL DEFAULT 255,
    PRIMARY KEY (id_category),
    UNIQUE INDEX id_category_UNIQUE (id_category ASC),
    UNIQUE INDEX slug_UNIQUE (slug ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_forum_section
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_forum_section (
    id_section INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_category INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NOT NULL,
    slug VARCHAR(255) NOT NULL,
    nb_posts INT UNSIGNED NOT NULL,
    nb_threads INT UNSIGNED NOT NULL DEFAULT 0,
    last_thread_id INT UNSIGNED NULL DEFAULT NULL,
    PRIMARY KEY (id_section),
    UNIQUE INDEX id_section_UNIQUE (id_section ASC),
    UNIQUE INDEX slug_UNIQUE (slug ASC),
    INDEX fk_section_belongs_to_category_idx (id_category ASC),
    CONSTRAINT fk_section_belongs_to_category
    FOREIGN KEY (id_category)
    REFERENCES ifocop_myshop.myshop_forum_category (id_category)
        ON DELETE CASCADE
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_forum_thread
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_forum_thread (
    id_thread INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_section INT UNSIGNED NOT NULL,
    topic VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    nb_posts INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL DEFAULT NULL,
    created_by_id_member INT UNSIGNED NULL DEFAULT NULL,
    updated_by_id_member INT UNSIGNED NULL DEFAULT NULL,
    last_post_id INT UNSIGNED NULL DEFAULT NULL,
    PRIMARY KEY (id_thread),
    UNIQUE INDEX id_thread_UNIQUE (id_thread ASC),
    UNIQUE INDEX slug_UNIQUE (slug ASC),
    INDEX fk_thread_forum_section_idx (id_section ASC),
    INDEX fk_thread_created_by_member_idx (created_by_id_member ASC),
    INDEX fk_thread_upated_by_member_idx (updated_by_id_member ASC),
    CONSTRAINT fk_thread_belongs_to_section
    FOREIGN KEY (id_section)
    REFERENCES ifocop_myshop.myshop_forum_section (id_section)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_thread_created_by_member
    FOREIGN KEY (created_by_id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_thread_updated_by_member
    FOREIGN KEY (updated_by_id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ifocop_myshop.myshop_forum_post
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ifocop_myshop.myshop_forum_post (
    id_post INT UNSIGNED NOT NULL AUTO_INCREMENT,
    content LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL DEFAULT NULL,
    created_by_id_member INT UNSIGNED NULL,
    updated_by_id_member INT UNSIGNED NULL,
    id_thread INT UNSIGNED NOT NULL,
    PRIMARY KEY (id_post),
    UNIQUE INDEX id_post_UNIQUE (id_post ASC),
    INDEX fk_post_created_by_member_idx (created_by_id_member ASC),
    INDEX fk_post_updated_by_member_idx (updated_by_id_member ASC),
    INDEX fk_post_thread_idx (id_thread ASC),
    CONSTRAINT fk_post_created_by_member
    FOREIGN KEY (created_by_id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_post_updated_by_member
    FOREIGN KEY (updated_by_id_member)
    REFERENCES ifocop_myshop.myshop_member (id_member)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_post_thread
    FOREIGN KEY (id_thread)
    REFERENCES ifocop_myshop.myshop_forum_thread (id_thread)
        ON DELETE CASCADE
        ON UPDATE CASCADE)
    ENGINE = InnoDB;

USE ifocop_myshop;

DELIMITER $$
USE ifocop_myshop$$
CREATE TRIGGER ifocop_myshop.AFTER_INSERT_forum_thread
AFTER INSERT ON myshop_forum_thread
FOR EACH ROW
    BEGIN
        UPDATE myshop_forum_section
        SET
            nb_threads = nb_threads + 1
        WHERE id_section = NEW.id_section;
    END$$

USE ifocop_myshop$$
CREATE TRIGGER ifocop_myshop.AFTER_DELETE_forum_thread
AFTER DELETE ON myshop_forum_thread
FOR EACH ROW
    BEGIN
        UPDATE myshop_forum_section s
        SET
            last_thread_id = (
                CASE WHEN nb_threads <= 1
                    THEN NULL
                ELSE (
                    SELECT t.id_thread
                    FROM myshop_forum_thread t
                        INNER JOIN myshop_forum_post p ON t.last_post_id = p.id_post
                    WHERE t.id_section = s.id_section
                    ORDER BY p.created_at DESC
                    LIMIT 1
                )
                END
            ),
            nb_threads = nb_threads - 1
        WHERE id_section = OLD.id_section;
    END$$

USE ifocop_myshop$$
CREATE TRIGGER ifocop_myshop.AFTER_INSERT_forum_post
AFTER INSERT ON myshop_forum_post
FOR EACH ROW
    BEGIN
        UPDATE myshop_forum_thread
        SET
            last_post_id = NEW.id_post,
            nb_posts = nb_posts + 1
        WHERE id_thread = NEW.id_thread;

        UPDATE myshop_forum_section
        SET
            last_thread_id = NEW.id_thread,
            nb_posts = nb_posts + 1
        WHERE id_section = (
            SELECT id_section
            FROM myshop_forum_thread
            WHERE id_thread = NEW.id_thread
        );
    END$$

USE ifocop_myshop$$
CREATE TRIGGER ifocop_myshop.AFTER_DELETE_forum_post
AFTER DELETE ON myshop_forum_post
FOR EACH ROW
    BEGIN
        UPDATE myshop_forum_thread t
        SET
            last_post_id = (
                CASE WHEN nb_posts <= 1
                    THEN NULL
                ELSE (
                    SELECT id_post
                    FROM myshop_forum_post p
                    WHERE p.id_thread = t.id_thread
                    ORDER BY created_at DESC
                    LIMIT 1
                )
                END
            ),
            nb_posts = nb_posts - 1
        WHERE id_thread = OLD.id_thread;
    END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
